### ISSUE TITLE
Pressing enter should leave the inline editor

### ISSUE THREAD

**Issue by zanodor** [PlayerMiller109/obsidian-keep-headings#1]
As there are no line break characters to be taken into consideration with headings, when user presses enter, it should break out of the editor.
Currently, when I want to break a long heading, I need to copy my heading, delete back, and on a new line paste what I want to carry over to a line.

So if user presses enter the remainder of the text should not be in the highlighted editor area anymore, but in main markdown text area.

**Comment by PlayerMiller109** [comment]
I've uploaded an update. You can uninstall the old one and download the new one to see if it has the feature you're looking for.

Test in v1.6.7 Sandbox Vault:

<img width="200" src="https://github.com/user-attachments/assets/b5c8bc5d-d766-47bd-90a0-9c54f4fc2341">

By the way, since I often accidentally click on the heading line, I've stopped adding a default background color in the update. If you still want the previous background, you can add the following CSS:

```css
.kh-bg {
  background: var(--background-modifier-cover);
}
```

**Comment by PlayerMiller109** [comment]
> you cannot enter the plugin's editor area.

It's accessible in my Sandbox Vault. You can't get in there without adding CSS?

**Comment by PlayerMiller109** [comment]
Here is my test without CSS:

<img width="200" src="https://github.com/user-attachments/assets/0180a107-dd1f-4e02-9945-a467d07ef729">

If you disable the CSS, restart Obsidian and then click on the heading, does it work?

Alternatively, you could test it in a sandbox vault; if the sandbox works fine, there might be a theme or plugin conflict in the original vault.

> cannot see the cursors where I'm clicking and when I alter text

I'm not quite sure about this sentence. Do you have a screenshot or a GIF?

**Comment by PlayerMiller109** [comment]
> cannot see the cursors where I'm clicking and when I alter text

I tweaked and reuploaded the code at 840b37e. May it fix your case.
