### ISSUE TITLE
[FR] Notify user about what was changed to what in upper right-hand notice

### ISSUE THREAD

**Issue by zanodor** [PlayerMiller109/obsidian-keep-headings#4]
The Obsidian notice should be sufficient, but if you have a 'merging changes automatically' issue from e.g. a frontmatter modified date update at the **same time**, the heading will look to be the same as it was before the replacement, but in the metadata cache the change was effected. So basically you cannot even rename back the heading, only if you discard the changes in the file with git, for example...
Or maybe I'm explaning it wrong: in the backlinked files the link was updated but not the parent file.

Just happened to me...Damnedest thing!

Easy for me to check with Github Desktop, but the average user will end up having bad links not knowing "what hit them".

So you'll need some error handling maybe...? Something, maybe a setting in the plugin that enables the user to check against he metadatacache what they have in the editor...?

Anyway, you can ignore this for a while saying the same thing could happen with a core Obsidian rename and even they don't do anything about freak show occurrences.
What they should do is make away with the merging changes problem, which if it happens before autosave, causes data loss.

**Comment by PlayerMiller109** [comment]
Hi, I'm not quite clear on what you mean. Are you saying that you receive a 'merging changes automatically' notice when you modify a heading? Or do you have other plugins for batch formatting headings, which rename them without going through the modal? If it's the latter, this plugin cannot achieve that. Since Obsidian itself renames a heading via the modal, the plugin should ensure the safety of data processing using the official method.
